/**
 * The one hand-written field on the Worker's environment.
 *
 * Everything else in `Env` is generated by `pnpm site:types` from wrangler.jsonc,
 * and that is the right default - hand-written binding interfaces drift from the
 * actual config, and the drift shows up as a runtime undefined rather than a
 * compile error.
 *
 * This is the exception, and the reason is structural rather than a preference:
 * a secret cannot appear in wrangler.jsonc, so it cannot appear in the generated
 * type either. Cloudflare rejects a name that is both a var and a secret, and the
 * config is where vars live.
 *
 * Declaring it here does not weaken the rule above. It adds exactly one field,
 * marked optional so that the absent case is the one TypeScript forces you to
 * handle - which matches how the policy already behaves: no judgment key means the
 * decision is made from onchain history alone, and never that a payment is
 * permitted.
 *
 * Set it with `pnpm site:secret`. Never in a file, never in this config.
 */

declare global {
  interface Env {
    /**
     * The judgment provider's key.
     *
     * Absent is a supported state, not a broken one: `judgeDocument` returns no
     * signals, and the policy treats a missing judgment as "no opinion" rather than
     * as "clear".
     */
    JUDGMENT_API_KEY?: string;
  }
}

export {};
